version: 2.1
jobs:
  build:
    docker:
    - image: circleci/python:3.7.0
    steps:
    - checkout
    # install dependencies
    - run: sudo pip3 install .
    - run: sudo pip3 install -r requirements.txt
    # download and prepare code climate test reporter
    - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - run: chmod +x ./cc-test-reporter
    - run: ./cc-test-reporter before-build
    # run tests
    - run: python3 -m pytest --cov-report=xml --cov=pyarxaas
    # run code climate test reporter and upload
    - run: ./cc-test-reporter -d after-build
  deploy:
    docker:
    - image: circleci/python:3.7.0
    steps:
    - checkout
    # install dependencies
    - run: sudo pip3 install twine
    # build
    - run: python3 setup.py sdist bdist_wheel
    # deploy to pypi
    - run: python3 -m twine upload -u $TWINE_USERNAME -p $TWINE_PASSWORD dist/*
workflows:
 version: 2
 build_and_release:
   jobs:
     - build
     - deploy:
         requires:
           - build
         filters:
           branches:
             only: master